Repository team4-campick/campick-client, pull requests merged in 2024-07, with the labels that each got.

#75 Lyj/campsite
  public/index.html
  src/App.js
  src/api/basedList.js
  src/api/imageList.js
  src/api/searchList.js
  src/api/url.js
  src/components/Campsite/SiteCard.jsx
  src/components/Campsite/SiteCard.module.css
  src/css/Campsite/Campsite.module.css
  src/css/Campsite/SiteDetail.module.css
  src/pages/Campsite/Campsite.jsx
  src/pages/Campsite/SiteDetail.jsx
Labels: front

#79 Ksj/signup
  src/components/Header.jsx
  src/pages/LoginPage.jsx
  src/pages/RegisterPage.jsx
Labels: front

#84 Lyj/campsite
  src/components/Campsite/ReviewCard.jsx
  src/components/Campsite/ReviewCard.module.css
  src/components/Campsite/ReviewCreateModal.jsx
  src/components/Campsite/ReviewCreateModal.module.css
  src/components/Campsite/SiteCard.jsx
  src/components/Campsite/SiteCard.module.css
  src/components/Header.jsx
  src/css/Campsite/SiteDetail.module.css
  src/pages/Campsite/Campsite.jsx
  src/pages/Campsite/SiteDetail.jsx
Labels: front

#123 Lyj/campsite
  public/images/MyPage/MyPageBanner.svg
  src/pages/LoginPage.jsx
  src/pages/MyPage/CustomerService.jsx
  src/pages/MyPage/MyPost.jsx
  src/pages/RegisterPage.jsx
Labels: front

#127 Lyj/mypage
  src/components/HeaderFooter/Header.jsx
  src/components/MyPage/SaleCard.jsx
  src/components/MyPage/SaleCard.module.css
  src/css/MyPage/Bingo.module.css
  src/css/MyPage/MyPage.module.css
  src/css/MyPage/MyPost.module.css
  src/css/MyPage/Transaction.module.css
  src/pages/LoginPage.jsx
  src/pages/MyPage/Bingo.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPost.jsx
  src/pages/MyPage/Purchase.jsx
  src/pages/MyPage/Sale.jsx
  src/store/inquiryStore.js
  src/store/store.js
Labels: front

#130 Lyj/mypage
  src/App.js
  src/components/MyPage/BingoCard.jsx
  src/components/MyPage/BingoCard.module.css
  src/css/MyPage/Bingo.module.css
Labels: front

#132 Lyj/mypage
  src/components/MyPage/BingoCard.module.css
  src/css/MyPage/Bingo.module.css
  src/pages/LoginPage.jsx
Labels: front

#140 Lyj/mypage
  src/components/MyPage/BingoCard.jsx
  src/components/MyPage/BingoCard.module.css
  src/css/MyPage/Bingo.module.css
  src/css/MyPage/CustomerService.module.css
  src/pages/MyPage/Bingo.jsx
Labels: front

#141 Lyj/campsite
  package-lock.json
  package.json
  src/assets/loading/loading.gif
  src/components/Campsite/ReviewCard.jsx
  src/components/Campsite/ReviewCard.module.css
  src/components/Campsite/ReviewCreateModal.jsx
  src/components/Campsite/ReviewEditModal.jsx
  src/components/Campsite/SiteCard.jsx
  src/components/Campsite/SiteCard.module.css
  src/components/Laoding/Loading.jsx
  src/components/Laoding/Loading.module.css
  src/css/Campsite/Campsite.module.css
  src/css/Campsite/SiteDetail.module.css
  src/pages/Campsite/Campsite.jsx
  src/pages/Campsite/SiteDetail.jsx
Labels: front

#145 feat: mypage modify
  src/pages/MyPage/EditInfo.jsx
  src/pages/MyPage/MyPage.jsx
Labels: front

#144 feat: campsite modify
  src/components/Campsite/StarRating.jsx
  src/pages/Campsite/SiteDetail.jsx
Labels: front

#148 Lyj/campsite
  src/components/Campsite/SiteCard.module.css
  src/constants/campsite.js
  src/css/Campsite/Campsite.module.css
  src/css/Campsite/SiteDetail.module.css
  src/pages/Campsite/Campsite.jsx
  src/pages/Campsite/SiteDetail.jsx
Labels: front

#149 Lyj/mypage
  src/App.css
  src/components/MyPage/BingoCard.module.css
  src/components/MyPage/CouponCard.jsx
  src/components/MyPage/SaleCard.jsx
  src/components/MyPage/SaleCard.module.css
  src/constants/coupon.js
  src/css/MyPage/Bingo.module.css
  src/css/MyPage/Coupon.module.css
  src/css/MyPage/CustomerService.module.css
  src/css/MyPage/EditInfo.module.css
  src/css/MyPage/MyPage.module.css
  src/css/MyPage/MyPageCommon.css
  src/css/MyPage/MyPost.module.css
  src/css/MyPage/Transaction.module.css
  src/pages/MyPage/Bingo.jsx
  src/pages/MyPage/Coupon.jsx
  src/pages/MyPage/MyPage.jsx
  src/pages/MyPage/MyPost.jsx
  src/pages/MyPage/Purchase.jsx
  src/pages/MyPage/Sale.jsx
Labels: front

#153 Lyj/mypage
  src/components/MyPage/CouponCard.jsx
  src/components/MyPage/CouponCard.module.css
  src/css/MyPage/Bingo.module.css
  src/css/MyPage/Coupon.module.css
  src/css/MyPage/CustomerService.module.css
  src/css/MyPage/EditInfo.module.css
  src/css/MyPage/MyPage.module.css
  src/pages/MyPage/Bingo.jsx
  src/pages/MyPage/Coupon.jsx
  src/pages/MyPage/CustomerService.jsx
  src/pages/MyPage/EditInfo.jsx
Labels: enhancement, front

#155 second merge to main
  src/App.css
  src/App.js
  src/components/BlogPost/BlogPostCard.module.css
  src/components/Market/SalePostCard.jsx
  src/components/Market/SalePostCard.module.css
  src/components/MyPage/CouponCard.jsx
  src/components/MyPage/CouponCard.module.css
  src/css/Contents/blogPostDetail.module.css
  src/css/Contents/blogPostWrite.module.css
  src/css/Contents/contentsBlog.module.css
  src/css/Market/Chat.module.css
  src/css/Market/Market.module.css
  src/css/Market/SaleDetail.module.css
  src/css/Market/SalePostWrite.module.css
  src/css/MyPage/Bingo.module.css
  src/css/MyPage/Coupon.module.css
  src/css/MyPage/CustomerService.module.css
  src/css/MyPage/EditInfo.module.css
  src/css/MyPage/MyPage.module.css
  src/hooks/useDropdown.css
  src/hooks/useGetConversations.js
  src/pages/Contents/BlogPostDetail.jsx
  src/pages/Contents/BlogPostEdit.jsx
  src/pages/Contents/BlogPostWrite.jsx
  src/pages/Market/Chat.jsx
  src/pages/Market/ChatList.jsx
  src/pages/Market/SaleDetail.jsx
  src/pages/Market/SalePostEdit.jsx
  src/pages/Market/SalePostWrite.jsx
  src/pages/MyPage/Bingo.jsx
  src/pages/MyPage/Coupon.jsx
  src/pages/MyPage/CustomerService.jsx
  src/pages/MyPage/EditInfo.jsx
  src/utils/validation.js
Labels: enhancement, front

#157 Lyj/mypage
  public/images/MyPage/bingoBanner.svg
  public/index.html
  src/App.css
  src/components/Campsite/ReviewCard.jsx
  src/components/Campsite/ReviewCreateModal.module.css
  src/components/HeaderFooter/Header.jsx
  src/components/HeaderFooter/header.module.css
  src/components/MyPage/BingoCard.jsx
  src/components/MyPage/BingoCard.module.css
  src/css/Campsite/Campsite.module.css
  src/css/Campsite/SiteDetail.module.css
  src/css/Contents/contentsVideo.module.css
  src/css/Event/event.module.css
  src/css/MyPage/Bingo.module.css
  src/css/MyPage/MyPage.module.css
  src/css/mainpage.module.css
  src/pages/Campsite/Campsite.jsx
  src/pages/Contents/ContentsVideo.jsx
  src/pages/Event/EventFinished.jsx
  src/pages/Event/EventProceeding.jsx
  src/pages/Mainpage.jsx
  src/pages/MyPage/Bingo.jsx
Labels: front, fixed

#159 PR to main
  package-lock.json
  package.json
  public/_redirects
  public/images/MyPage/bingoBanner.svg
  public/index.html
  src/App.css
  src/components/BlogPost/BlogPostCard.module.css
  src/components/BlogPost/QuillEditor.jsx
  src/components/BlogPost/QuillEditor.module.css
  src/components/Campsite/ReviewCard.jsx
  src/components/Campsite/ReviewCreateModal.module.css
  src/components/HeaderFooter/Header.jsx
  src/components/HeaderFooter/header.module.css
  src/components/Market/SalePostCard.jsx
  src/components/Market/SalePostCard.module.css
  src/components/MyPage/BingoCard.jsx
  src/components/MyPage/BingoCard.module.css
  src/constants/market.js
  src/css/Campsite/Campsite.module.css
  src/css/Campsite/SiteDetail.module.css
  src/css/Contents/blogPostDetail.module.css
  src/css/Contents/blogPostWrite.module.css
  src/css/Contents/contentsBlog.module.css
  src/css/Contents/contentsVideo.module.css
  src/css/Event/event.module.css
  src/css/Market/Chat.module.css
  src/css/Market/Market.module.css
  src/css/Market/SaleDetail.module.css
  src/css/Market/SalePostWrite.module.css
  src/css/MyPage/Bingo.module.css
  src/css/MyPage/MyPage.module.css
  src/css/mainpage.module.css
  src/hooks/useDropdown.css
  src/hooks/useDropdown.jsx
  src/pages/Campsite/Campsite.jsx
  src/pages/Contents/ContentsBlog.jsx
  src/pages/Contents/ContentsVideo.jsx
  src/pages/Event/EventFinished.jsx
  src/pages/Event/EventProceeding.jsx
  src/pages/Mainpage.jsx
  src/pages/Market/Chat.jsx
  src/pages/Market/ChatList.jsx
  src/pages/Market/Market.jsx
  src/pages/Market/SaleDetail.jsx
  src/pages/Market/SalePostEdit.jsx
  src/pages/Market/SalePostWrite.jsx
  src/pages/MyPage/Bingo.jsx
  src/utils/formatChatTime.js
Labels: front

#160 Lyj/mypage
  src/App.css
  src/components/HeaderFooter/Header.jsx
  src/components/HeaderFooter/footer.module.css
  src/components/HeaderFooter/header.module.css
  src/css/mainpage.module.css
  src/pages/Mainpage.jsx
  src/pages/MyPage/Bingo.jsx
  src/pages/MyPage/Coupon.jsx
Labels: front, fixed

#162 PR to main
  src/App.css
  src/components/HeaderFooter/Header.jsx
  src/components/HeaderFooter/footer.module.css
  src/components/HeaderFooter/header.module.css
  src/components/Market/SalePostCard.jsx
  src/components/Market/SalePostCard.module.css
  src/css/Contents/blogPostWrite.module.css
  src/css/Contents/contentsBlog.module.css
  src/css/Market/Chat.module.css
  src/css/Market/ChatColor.css
  src/css/Market/SaleDetail.module.css
  src/css/mainpage.module.css
  src/hooks/useDropdown.css
  src/hooks/useDropdown.jsx
  src/pages/Mainpage.jsx
  src/pages/Market/Chat.jsx
  src/pages/MyPage/Bingo.jsx
  src/pages/MyPage/Coupon.jsx
Labels: front

#164 favicon
  public/favicon.ico
Labels: front

#165 style: my page design modify
  src/css/MyPage/MyPage.module.css
Labels: front

#166 additional pr to main
  src/css/MyPage/MyPage.module.css
Labels: front

#169 Additional PR
  src/css/mainpage.module.css
Labels: front

#186 Lyj/mypage
  src/components/Campsite/ReviewCard.jsx
  src/components/Campsite/ReviewCreateModal.jsx
  src/components/Campsite/ReviewEditModal.jsx
  src/pages/Campsite/SiteDetail.jsx
  src/pages/LoginPage.jsx
  src/pages/MyPage/Bingo.jsx
  src/pages/MyPage/Coupon.jsx
  src/pages/MyPage/CustomerService.jsx
  src/pages/MyPage/EditInfo.jsx
Labels: front, fixed, refactoring

#188 [MyPage] 리팩토링
  src/components/Campsite/ReviewCreateModal.jsx
  src/components/Campsite/ReviewEditModal.jsx
  src/pages/MyPage/Bingo.jsx
  src/pages/MyPage/CustomerService.jsx
  src/pages/MyPage/EditInfo.jsx
  src/pages/MyPage/MyPost.jsx
Labels: front, refactoring

#189 fix: incorrect variable name error
  src/pages/MyPage/MyPost.jsx
Labels: bug, front, fixed
